update InputProcessor.cs
TehAbyss/HashCode pull request #10
Opened 2020-01-28 07:26 UTC by rosethub

2020-01-28 08:17 UTC, TehAbyss requested changes
Please look over my review.

2020-01-28 08:17 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +
Follow this project coding convention. Move the using references inside the namespace.

2020-01-28 08:17 UTC, TehAbyss commented on Controller/InputProcessor.cs
> -        //first commit
Remove this comment line, it is not needed

2020-01-28 08:17 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +        public int _totalPhoto;
You probably don't need member variables to store anything. The output result from your method should produce a PhotoCollection which contains all the information you get from parsing the input file.

2020-01-28 08:17 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +        private void ReadInputFile()
It might be simpler to just combine the ReadInputFile and GetInputData methods into one. In ReadInputFile, you are already looping on each line. You can parse when you already processing the line.

I recommend your function signature is PhotoCollection ReadInputFile(string filePath);

2020-01-28 08:17 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +                using (var streamReader = new StreamReader(fileStream, Encoding.UTF8))
I'm not sure if Encoding.UTF8 is necesssary

2020-01-28 08:17 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +
Add using HashPhotoSlideshow.Model;

2020-01-28 08:17 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +                    photo.Tags.Add(words[pos++]);
The code looks like it will work. I don't see why you would have runtime errors.

2020-01-28 08:17 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +                _photo.Add(photo);
Don't forget to also set the photo.Id property.

2020-01-28 08:24 UTC, rosethub commented
Ok, thanks.  Will update the code.

On Tue, Jan 28, 2020, 12:17 AM TehAbyss <notifications@github.com> wrote:

> *@TehAbyss* requested changes on this pull request.
>
> Please look over my review.
> ------------------------------
>
> In Controller/InputProcessor.cs
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10#discussion_r371649107>
> :
>
> > +using System;
> +using System.Collections.Generic;
> +using System.IO;
> +using System.Text;
> +
>
> Follow this project coding convention. Move the using references inside
> the namespace.
> ------------------------------
>
> In Controller/InputProcessor.cs
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10#discussion_r371649203>
> :
>
> >  namespace HashPhotoSlideshow.Controller
>  {
>      public class InputProcessor
>      {
> -        //first commit
>
> Remove this comment line, it is not needed
> ------------------------------
>
> In Controller/InputProcessor.cs
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10#discussion_r371649646>
> :
>
> > +        List<string> _lines;
> +        public List<Photo> _photo;
> +        public int _totalPhoto;
>
> You probably don't need member variables to store anything. The output
> result from your method should produce a PhotoCollection which contains all
> the information you get from parsing the input file.
> ------------------------------
>
> In Controller/InputProcessor.cs
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10#discussion_r371651361>
> :
>
> >  namespace HashPhotoSlideshow.Controller
>  {
>      public class InputProcessor
>      {
> -        //first commit
> +        List<string> _lines;
> +        public List<Photo> _photo;
> +        public int _totalPhoto;
> +
> +        public InputProcessor()
> +        {
> +            _lines = new List<string>();
> +            _photo = new List<Photo>();
> +            _totalPhoto = 0;
> +        }
> +
> +        private void ReadInputFile()
>
> It might be simpler to just combine the ReadInputFile and GetInputData
> methods into one. In ReadInputFile, you are already looping on each line.
> You can parse when you already processing the line.
>
> I recommend your function signature is PhotoCollection
> ReadInputFile(string filePath);
> ------------------------------
>
> In Controller/InputProcessor.cs
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10#discussion_r371651959>
> :
>
> > +        {
> +            _lines = new List<string>();
> +            _photo = new List<Photo>();
> +            _totalPhoto = 0;
> +        }
> +
> +        private void ReadInputFile()
> +        {
> +            //string path = "..\\..\\..\\inputFile.txt";
> +            string path = "inputFile.txt";
> +
> +            if (File.Exists(path))
> +            {
> +                List<string> list = new List<string>();
> +                FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read);
> +                using (var streamReader = new StreamReader(fileStream, Encoding.UTF8))
>
> I'm not sure if Encoding.UTF8 is necesssary
> ------------------------------
>
> In Controller/InputProcessor.cs
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10#discussion_r371656635>
> :
>
> > @@ -1,7 +1,79 @@
> +using System;
> +using System.Collections.Generic;
> +using System.IO;
> +using System.Text;
> +
>
> Add using HashPhotoSlideshow.Model;
> ------------------------------
>
> In Controller/InputProcessor.cs
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10#discussion_r371656831>
> :
>
> > +                string[] words = _lines[i].Split(' ');
> +
> +                Photo photo = new Photo();
> +
> +                int pos = 0;
> +
> +                if (words[pos++] == "H")
> +                    photo.Orientation = Orientation.Horizontal;
> +                else
> +                    photo.Orientation = Orientation.Vertical;
> +
> +                int count = Int32.Parse(words[pos++]);
> +
> +                for(int j = 0; j < count; j++)
> +                {
> +                    photo.Tags.Add(words[pos++]);
>
> The code looks like it will work. I don't see why you would have runtime
> errors.
> ------------------------------
>
> In Controller/InputProcessor.cs
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10#discussion_r371657152>
> :
>
> > +
> +                int pos = 0;
> +
> +                if (words[pos++] == "H")
> +                    photo.Orientation = Orientation.Horizontal;
> +                else
> +                    photo.Orientation = Orientation.Vertical;
> +
> +                int count = Int32.Parse(words[pos++]);
> +
> +                for(int j = 0; j < count; j++)
> +                {
> +                    photo.Tags.Add(words[pos++]);
> +                }
> +
> +                _photo.Add(photo);
>
> Don't forget to also set the photo.Id property.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TehAbyss/HashPhotoSlideshow/pull/10?email_source=notifications&email_token=AOMBIJSBMVAA2WQFJ5C7GH3Q77SZLA5CNFSM4KMNUT4KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCTIAX5Y#pullrequestreview-349178871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOMBIJTNRZVBZSBLIYSAUJ3Q77SZLANCNFSM4KMNUT4A>
> .
>

2020-01-29 06:21 UTC, TehAbyss requested changes

2020-01-29 06:21 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +        public List<Photo> _photo;
No need for member variables. Create a static function that takes in a path and returns a PhotoCollection. Right now there is no way for a user to select an input file? Do you expect to hardcode a path to the input file?

2020-01-29 06:21 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +        {
No need for constructor. All functionality can go in the static ReadInputFile function.

2020-01-29 06:21 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +            string path = "inputFile.txt";
Your function should take in a string path parameter? Remove this hardcoded path variable.

2020-01-29 06:21 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +                FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read);
Enclose filestream in a using () scope too.

2020-01-29 06:21 UTC, TehAbyss commented on Controller/InputProcessor.cs
> +        }
Return a PhotoCollection object

2020-01-30 06:44 UTC, TehAbyss approved these changes

2020-01-30 06:45 UTC, merged